[package]
name = "hello_rl"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.18"

# Enable fast compiles for development
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
